logging:
  file:
    max-history: 7
  level:
    root: info
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
    org.hibernate:
#      SQL: DEBUG
      orm.jdbc.bind: TRACE
  path: logs

spring:
  autoconfigure:
    excludd: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: l4oSu3Es7bivTu+Dh1pRMfAmaiIEgBiW67vy/orxmXBPq/gt2fVkQsQO2t3g8CZzHzgO1OwfMzdBHEHRQ+3Pb+5RAmPZFb7Dmu7QTX/QsgXxBMlhIuHO+nbk8eoABV46QIQSINJLinXH7JbrkyBi52gjUTh4/YByBGWe6WkCF/o=
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hZqQ2BVOOunIO1U38O1ciw==
    password: aKHpqzCLY+b3EE/oA7IENg==
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      validation-timeout: 10000
      maxLifetime: 1790000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate:
      default_batch_fetch_size: 100
      format_sql: true
      show_sql: true

    hibernate:
      ddl-auto: update

  messages:
    basename: i18n/exception
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  jwt:
    secret: VyAHb65Ww8V1vj2FXHMS6g==

  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 50MB

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: dT86SQtzNRCqfCtRIiA/TmIvQGotdTqExR2RKqw80Yw=
    credentials:
      access-key: COG9cbWGCwLg2h2iLmmOgaPMo5tU5yAN6k8JIZ/cfTw=
      secret-key: JcHJHjF3vuy1ZznEcc+IT3F1i2xT3QwkThF12PsIsu7Md7EYh0tWyyr8cXuWMJJ/

photoism:
  encrypt:
    key: Uyn+GjQZ1to6HCyxxnCv7yyY8OGI9uhTiVkWEPAqOz4=
  mail:
    chgpassurl: https://dev.cms.seobuk.kr/resetpassword
    smtp:
      host: smtp.gmail.com
      port: 587
      user: support@ebiznow.co.kr
      pass: bvGfFF8Wz17b5awiQJuLZA==
      mail: support@ebiznow.co.kr